// <auto-generated />
using System;
using LostAndFoundAgency.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace LostAndFoundAgency.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LostAndFoundAgency.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.FoundItem", b =>
                {
                    b.Property<int>("FoundItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoundItemId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateFound")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FinderId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Очікує обробки");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("FoundItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FinderId");

                    b.HasIndex("LocationId");

                    b.HasIndex("DateFound");

                    b.HasIndex("Status");

                    b.HasIndex("CategoryId", "Status");

                    b.ToTable("FoundItems", t =>
                        {
                            t.HasCheckConstraint("CK_FoundItems_Status", "[Status] IN (N'Очікує обробки', N'Закрито (Повернуто)', N'Відхилено')");
                        });
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationName")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.LostRequest", b =>
                {
                    b.Property<int>("LostRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LostRequestId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateLost")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Очікує обробки");

                    b.HasKey("LostRequestId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PersonId");

                    b.HasIndex("DateLost");

                    b.HasIndex("Status");

                    b.HasIndex("CategoryId", "Status");

                    b.ToTable("LostRequests", t =>
                        {
                            t.HasCheckConstraint("CK_LostRequests_Status", "[Status] IN (N'Очікує обробки', N'Закрито (Знайдено)', N'Відхилено')");
                        });
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("FoundItemId")
                        .HasColumnType("int");

                    b.Property<int>("LostRequestId")
                        .HasColumnType("int");

                    b.Property<int>("MatchPercent")
                        .HasColumnType("int");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Потенційний");

                    b.HasKey("MatchId");

                    b.HasIndex("FoundItemId");

                    b.HasIndex("LostRequestId");

                    b.HasIndex("MatchStatus");

                    b.HasIndex("FoundItemId", "LostRequestId")
                        .IsUnique();

                    b.ToTable("Matches", t =>
                        {
                            t.HasCheckConstraint("CK_Matches_MatchPercent", "[MatchPercent] >= 0 AND [MatchPercent] <= 100");
                            t.HasCheckConstraint("CK_Matches_Status", "[MatchStatus] IN (N'Потенційний', N'Підтверджено', N'Відхилено')");
                        });
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("PersonId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Return", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FoundItemId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ReturnId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("FoundItemId")
                        .IsUnique();

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.FoundItem", b =>
                {
                    b.HasOne("LostAndFoundAgency.Models.Category", "Category")
                        .WithMany("FoundItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAndFoundAgency.Models.Employee", "Employee")
                        .WithMany("AssignedFoundItems")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LostAndFoundAgency.Models.Person", "Finder")
                        .WithMany("FoundItems")
                        .HasForeignKey("FinderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAndFoundAgency.Models.Location", "Location")
                        .WithMany("FoundItems")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Employee");

                    b.Navigation("Finder");

                    b.Navigation("Location");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.LostRequest", b =>
                {
                    b.HasOne("LostAndFoundAgency.Models.Category", "Category")
                        .WithMany("LostRequests")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAndFoundAgency.Models.Employee", "Employee")
                        .WithMany("AssignedLostRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LostAndFoundAgency.Models.Location", "Location")
                        .WithMany("LostRequests")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAndFoundAgency.Models.Person", "Person")
                        .WithMany("LostRequests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Employee");

                    b.Navigation("Location");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Match", b =>
                {
                    b.HasOne("LostAndFoundAgency.Models.FoundItem", "FoundItem")
                        .WithMany("Matches")
                        .HasForeignKey("FoundItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAndFoundAgency.Models.LostRequest", "LostRequest")
                        .WithMany("Matches")
                        .HasForeignKey("LostRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoundItem");

                    b.Navigation("LostRequest");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Return", b =>
                {
                    b.HasOne("LostAndFoundAgency.Models.Employee", "Employee")
                        .WithMany("ProcessedReturns")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAndFoundAgency.Models.FoundItem", "FoundItem")
                        .WithOne("Return")
                        .HasForeignKey("LostAndFoundAgency.Models.Return", "FoundItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAndFoundAgency.Models.Person", "Person")
                        .WithMany("Returns")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("FoundItem");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Category", b =>
                {
                    b.Navigation("FoundItems");

                    b.Navigation("LostRequests");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Employee", b =>
                {
                    b.Navigation("AssignedFoundItems");

                    b.Navigation("AssignedLostRequests");

                    b.Navigation("ProcessedReturns");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.FoundItem", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Location", b =>
                {
                    b.Navigation("FoundItems");

                    b.Navigation("LostRequests");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.LostRequest", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("LostAndFoundAgency.Models.Person", b =>
                {
                    b.Navigation("FoundItems");

                    b.Navigation("LostRequests");

                    b.Navigation("Returns");
                });
#pragma warning restore 612, 618
        }
    }
}
